### ISSUE TITLE
Question about training strategy

### ISSUE THREAD

**Issue by slcheng97** [qq456cvb/KeypointNet#2]
As for the training process on the KeypointNet dataset, should I train my model for each class one by one? Or can I train it on the whole dataset?

**Comment by qq456cvb** [comment]
Currently, our released code trains the model for each class one by one considering intra-class consistency. However, it should be straightforward to train a universal network (by setting number of keypoints to the maximum among classes).

**Comment by slcheng97** [comment]
Got it, thanks a lot!
