### ISSUE TITLE
Any plan to release the annotation tool?

### ISSUE THREAD

**Issue by Kulbear** [qq456cvb/KeypointNet#4]
Hi,

We are working on a project that has similar annotation format and we'd like to annotate some of the keypoints on the model as well. Would you please to tell whether you have plan to release the annotation tool as well?

Thank you

**Comment by qq456cvb** [comment]
We are sorry that this annotation tool is patent protected. However, you may find this repo https://github.com/alvinwan/antsy3d helpful, which is also based on ThreeJS.

**Comment by Kulbear** [comment]
Thanks for letting us know about it.

The referred repo looks interesting, thank you!
