### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by LuoS2016** [qq456cvb/KeypointNet#5]
Hi. Could you please provide the install dependencies of this code? Some network models cannot run without knowing the install dependencies. Thank you very much.

**Comment by qq456cvb** [comment]
Hi, Luo, have you tried installing dependencies as suggested in `benchmark_scripts/README.md`?

**Comment by LuoS2016** [comment]
Yes, I have tried. But some network models cannot run. I want to know something more detailed, especially the version of the torch.

**Comment by qq456cvb** [comment]
Hi, we've added `env.yml` and `setup_env.sh` to help set up the environment. Could you try it and see if you meet any problem?

**Comment by qq456cvb** [comment]
Hi, we've added `env.yml` and `setup_env.sh` to help set up the environment. Could you try it and see if you meet any problem?

**Comment by LuoS2016** [comment]
OK，thanks a lot.
