### ISSUE TITLE
Full annotation files required

### ISSUE THREAD

**Issue by xspkwy** [qq456cvb/KeypointNet#6]
Hello, could you please provide all annotation files? Now there is only _chair.json_

**Comment by qq456cvb** [comment]
Our full dataset can be downloaded from Google Drive or OneDrive. Annotated JSON data is placed under annotations, as stated in ReadMe (https://github.com/qq456cvb/KeypointNet#keypoint-data).

**Comment by xspkwy** [comment]
Oh, I miss the “annotations” folder in the Google Drive since it is not obvious.
Thank you!
